### ISSUE TITLE
install problem

### ISSUE THREAD

**Issue by ohthetrees** [ctberthiaume/gdcp#11]
Haven't had time to troubleshoot at all, so perhaps a problem on my end. This is on a pretty vanilla OS X 10.10 system with system python.

```
Sagan:Downloads cedar$ pip install pydrive --upgrade
Requirement already up-to-date: pydrive in /Library/Python/2.7/site-packages
Requirement already up-to-date: google-api-python-client>=1.2 in /Library/Python/2.7/site-packages (from pydrive)
Requirement already up-to-date: PyYAML>=3.0 in /Library/Python/2.7/site-packages (from pydrive)
Requirement already up-to-date: httplib2>=0.8 in /Library/Python/2.7/site-packages (from google-api-python-client>=1.2->pydrive)
Requirement already up-to-date: oauth2client>=1.4.6 in /Library/Python/2.7/site-packages (from google-api-python-client>=1.2->pydrive)
Requirement already up-to-date: six>=1.6.1 in /Library/Python/2.7/site-packages (from google-api-python-client>=1.2->pydrive)
Requirement already up-to-date: uritemplate>=0.6 in /Library/Python/2.7/site-packages (from google-api-python-client>=1.2->pydrive)
Requirement already up-to-date: pyasn1==0.1.7 in /Library/Python/2.7/site-packages (from oauth2client>=1.4.6->google-api-python-client>=1.2->pydrive)
Requirement already up-to-date: pyasn1-modules==0.0.5 in /Library/Python/2.7/site-packages (from oauth2client>=1.4.6->google-api-python-client>=1.2->pydrive)
Requirement already up-to-date: rsa==3.1.4 in /Library/Python/2.7/site-packages (from oauth2client>=1.4.6->google-api-python-client>=1.2->pydrive)
Requirement already up-to-date: simplejson>=2.5.0 in /Library/Python/2.7/site-packages (from uritemplate>=0.6->google-api-python-client>=1.2->pydrive)
Sagan:Downloads cedar$ git clone https://github.com/ctberthiaume/gdcp.git
Cloning into 'gdcp'...
remote: Counting objects: 132, done.
remote: Total 132 (delta 0), reused 0 (delta 0), pack-reused 132
Receiving objects: 100% (132/132), 31.82 KiB | 0 bytes/s, done.
Resolving deltas: 100% (80/80), done.
Checking connectivity... done.
Sagan:Downloads cedar$ gdcp/gdcp 
Traceback (most recent call last):
  File "gdcp/gdcp", line 1021, in <module>
    main()
  File "gdcp/gdcp", line 39, in main
    do_setup()
  File "gdcp/gdcp", line 127, in do_setup
    authorize()
  File "gdcp/gdcp", line 86, in authorize
    gauth.CommandLineAuth()
  File "/Library/Python/2.7/site-packages/pydrive/auth.py", line 69, in _decorated
    code = decoratee(self, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/pydrive/auth.py", line 198, in CommandLineAuth
    authorize_url = self.GetAuthUrl()
  File "/Library/Python/2.7/site-packages/pydrive/auth.py", line 385, in GetAuthUrl
    return self.flow.step1_get_authorize_url()
  File "/Library/Python/2.7/site-packages/oauth2client/util.py", line 137, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/oauth2client/client.py", line 1827, in step1_get_authorize_url
    return _update_query_params(self.auth_uri, query_params)
  File "/Library/Python/2.7/site-packages/oauth2client/client.py", line 435, in _update_query_params
    parts = urllib.parse.urlparse(uri)
AttributeError: 'Module_six_moves_urllib_parse' object has no attribute 'urlparse'
```

**Comment by ctberthiaume** [comment]
I think the issue is the version of six that is being used. It should be a version >= 1.6.1, and pip will install the correct version when installing pydrive, but the version loaded is the incorrect version. On my system (10.10.2) pip installs six.py version 1.9.0 to `/Library/Python/2.7/site-packages`, but `/usr/bin/python` loads version 1.4.1 from `/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python`.  You can confirm which version is getting loaded with:

```sh
/usr/bin/python -c 'import six; print six.__version__; print six.__file__'
```

This looks to be caused by the fact that the pip installed by easy_install is not modifying the python library search path correctly to make sure the newest version of six takes precedence. In my case, the library search path has `/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python` ahead of `/Library/Python/2.7/site-packages`. This means that even though I can upgrade to six 1.9.0, version 1.4.1 is always used instead. You can check your library search path with:

```sh
/usr/bin/python -c 'import sys, pprint; pprint.pprint(sys.path)'
```

I don't know how to fix Apple's version of Python / easy_install to make this work properly. It seems to be incompatible with the pip installed via `/usr/bin/easy_install`. See https://github.com/pypa/pip/issues/2468 for an extended discussion of the problem and possible workarounds.

What I do to get a working version of PyDrive is use a version of python installed through macports or use a virtualenv library setup. You could also set your `PYTHONPATH` env variable to put `/Library/Python/2.7/site-packages` ahead of `/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python`. Otherwise, I think you'll have to make changes to some of the system files for easy_install, pip, or the places where these tools set up the search paths.

**Comment by ohthetrees** [comment]
Thank you for the extremely detailed reply. Shame it doesn't work "out of the box". I wonder if the README should be updated with instructions, or at least a note about the issue.

**Comment by ctberthiaume** [comment]
Good point. I've updated the README to reference this issue and suggest workarounds.

**Comment by philfung** [comment]
ctberthiaume's explanation is correct.  I had the same issue and used 'export PYTHONPATH="/Library/Python/2.7/site-packages"' to fix
