### ISSUE TITLE
Trouble installing

### ISSUE THREAD

**Issue by ohthetrees** [ctberthiaume/gdcp#18]
OSX 10.10.4. Could there be an undocumented gdcp prerequisite?

```
cmckay$ which python
/opt/local/bin/python
sudo pip install --upgrade pydrive
[snip]
sudo pip install --upgrade backoff
[snip]
cmckay$ gdcp
Traceback (most recent call last):
  File "/usr/local/bin/gdcp", line 3, in <module>
    import apiclient.errors
ImportError: No module named apiclient.errors
```

**Comment by ctberthiaume** [comment]
No, installing pydrive should bring in the Google api library that contains apiclient. I actually had exactly this problem yesterday. It turned out that the `pip` that was being run in the context of `sudo` was not tied to the Python installation that my normal user uses. So I `pip` installed to one Python location and then `gdcp` ran with a different Python which didn't have any prereqs installed.

**Comment by ohthetrees** [comment]
Ug, I was sure that I closed this bug yesterday after I discovered a similar resolution! I resolved mine by installing the mac ports version of pip, then installing pydrive and backoff again. Anyway, thanks for looking into it.
