### ISSUE TITLE
Maybe why resumable uploads not working?

### ISSUE THREAD

**Issue by ohthetrees** [ctberthiaume/gdcp#5]
Is it possible that resumable uploads aren't working because you never try the resume the upload?

In the following code (around line 438), you increment the resumable_retries, but I don't see that you actually retry anything. I'm probably just not understanding what you are doing, but it would be funny if this was the cause!

```
                    else:
                        delay = 2 ** resumable_retries
                        log.warning("HTTP error %d, retrying in %ds ..." %
                                    (e.resp.status, delay))
                        time.sleep(delay)
                        resumable_retries += 1
```

**Comment by ctberthiaume** [comment]
The retry happens when next_chunk() is called during the next iteration of the while loop.  I'm pretty sure the loop is not exited prematurely because you can see at least one retry with increasing delay happen in the output for issue https://github.com/ctberthiaume/gdcp/issues/4.  From what I've seen resumable uploads which encounter a 50X error will either fail as in issue https://github.com/ctberthiaume/gdcp/issues/4 (looks like a bug in the google api python client) or will receive a 404 or 410 error the next time next_chunk is called and the whole upload for that file will restart.

**Comment by ohthetrees** [comment]
So if I want to add another except that catches everything you haven't already caught, would it make sense to model it on your `# start upload all over` code chunk near line 391?

Maybe it's too dangerous to catch everything? Maybe we should only catch things we've seen so far? Like the KeyError and the SSLError that we saw once. On the other hand, isn't it always work a try to restart the upload? What do you think?

**Comment by ctberthiaume** [comment]
I pushed a new commit to add upload restarts when a KeyError or ssl.SSLError is encountered.  If we see more different exceptions we can broaden the net.  It probably wouldn't hurt to catch everything.  Even if something goes wrong there's always the MD5 final check to verify that the upload worked.  But for now let's keep it as specific as possible until that position becomes untenable.

**Comment by ohthetrees** [comment]
Great! Testing with a 1 TB upload now.  Might as well close this.  For the record, 67c1d48d27198fef9036873bc66e09cdb80bb5d3 addresses the KeyError and SSLError.
